name: CI com Secret

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm test

      - name: Usar secret do token
        run: |
          echo "Usando meu token seguro para deploy!"
          echo "Token: ${{ secrets.MY_API_TOKEN }}"
